### ISSUE TITLE
nm:ManufacturerOrSourceName in XML to RDF conversion?

### ISSUE THREAD

**Issue by mdeagen** [tetherless-world/nanomine-graph#23]
### Issue

Material source (manufacturer) information from the XML files is not being converted to RDF.

### Description

Researchers often report the manufacturer or distributor of materials that were purchased for a study. This information is curated into NanoMine as a `<ManufacturerOrSourceName>` element, which can be nested beneath a `<MatrixComponent>`, `<FillerComponent>`, or `<ParticleSurfaceTreatment>` element.

See the below example from sample L169_S2_Song_2012:
![image](https://user-images.githubusercontent.com/43749866/86290751-f57b5300-bbbb-11ea-9b57-ffb9b50eafb0.png)

Ideally, these sources would have their own URIs, but at a minimum the strings should be accessible from a SPARQL query.

**Comment by rashidsabbir** [comment]
I've updated so that ```SELECT * WHERE {  ?matrix sio:hasAttribute [ a nm:ManufacturerOrSourceName ; sio:hasValue ?manufacturer_name] .}``` works as expected.

**Comment by mdeagen** [comment]
Components with role of a `nm:Matrix` now have this info, but what about those components that have role of a `nm:Filler` or `nm:SurfaceTreatment`? Both are returning 0 results, which is not reflective of the XML data (for example in the screenshot above with a SurfaceTreatment that has manufacturer Alfa Aesar).
