### ISSUE TITLE
Change in modeling of Processing Steps?

### ISSUE THREAD

**Issue by mdeagen** [tetherless-world/nanomine-graph#27]
The following query used to work on QA & production, but now only works on production (QA returns 0 results):

```
PREFIX nm: <http://nanomine.org/ns/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  ?sample a nm:PolymerNanocomposite ;
          prov:wasGeneratedBy [ a sio:Procedure ;
                                sio:hasPart [ a [ rdfs:label ?label ] ]
                              ]
}
```

Are we changing the way these processing steps are stored?

**Comment by mdeagen** [comment]
Following up, the SPARQL query corresponding to [this chart](https://materialsmine.org/wi/about?view=gallery&uri=http://semanticscience.org/resource/Chart&gt=423e726cf4623c2c) returns 48 results on the production endpoint, but returns an **empty set** on the QA endpoint.

**Comment by rashidsabbir** [comment]
I've updated the setl script to address this issue. Turns out the @id line was in the wrong place, so the property prov:wasGeneratedBy was being assigned to a blank node rather than the sample uri

**Comment by mdeagen** [comment]
Confirmed (with below query) that the processing steps issue has been fixed.

```
# Show ranked list of Processing steps, in descending order based on number of samples
PREFIX nm: <http://nanomine.org/ns/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
SELECT ?process (COUNT(DISTINCT ?sample) AS ?NumberOfSamples) WHERE {
  ?sample a nm:PolymerNanocomposite ;
          prov:wasGeneratedBy/sio:hasPart [ a ?process ]
      
} 
GROUP BY ?process
ORDER BY DESC (?NumberOfSamples)
```
**9** results
